const QueryType = {
    LOCATOR: 'LOCATOR',
    CLEARANCE_ORDER: 'CLEARANCE_ORDER',
    TIMESTAMP: 'TIMESTAMP',
    CLEARANCE_ORDER_AND_SN: 'CLEARANCE_ORDER_AND_SN',
    ERROR: 'ERROR',
}

export { QueryType }
