const VerifyNotExistProofStatus = {
    OK_INDEX_VALUE_NOT_FOUND: 'OK_INDEX_VALUE_NOT_FOUND',
    OK_CLEARANCE_NOT_BETWEEN_SEARCH_TIME: 'OK_CLEARANCE_NOT_BETWEEN_SEARCH_TIME',
    OK_RECEIPT_AND_MERKLE_PROOF_SHOULD_BE_END_OF_PROOF: 'OK_RECEIPT_AND_MERKLE_PROOF_SHOULD_BE_END_OF_PROOF',
    ERROR_INDEX_VALUE_IN_PAIR: 'ERROR_INDEX_VALUE_IN_PAIR',
    ERROR_ROOT_HASH_ERROR: 'ERROR_ROOT_HASH_ERROR',
    ERROR_SLICE_ERROR: 'ERROR_SLICE_ERROR',
    ERROR_SIGNATURE: 'ERROR_SIGNATURE',
    CLEARANCE_RECORD_ERROR: 'CLEARANCE_RECORD_ERROR',
}

export { VerifyNotExistProofStatus }
